INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (1, 'Комедия');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (2, 'Драма');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (3, 'Мультфильм');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (4, 'Триллер');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (5, 'Документальный');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (6, 'Боевик');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_ID,MPA_NAME)
VALUES (1,'G');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_ID,MPA_NAME)
VALUES (2,'PG');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_ID,MPA_NAME)
VALUES (3,'PG-13');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_ID,MPA_NAME)
VALUES (4,'R');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_ID,MPA_NAME)
VALUES (5,'NC-17');

INSERT INTO PUBLIC.EVENT_TYPE (TYPE_ID,TYPE_NAME)
VALUES (1,'LIKE'),
       (2,'REVIEW'),
       (3,'FRIEND');

INSERT INTO PUBLIC.OPERATION (OPERATION_ID,OPERATION_NAME)
VALUES (1,'REMOVE'),
       (2,'ADD'),
       (3,'UPDATE');

