INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Комедия');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Драма');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Мультфильм');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Триллер');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Документальный');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_NAME)
VALUES ('Боевик');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('G');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('PG');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('PG-13');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('R');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('NC-17');

INSERT INTO PUBLIC.EVENT_TYPE (TYPE_NAME)
VALUES ('LIKE'),
       ('REVIEW'),
       ('FRIEND');

INSERT INTO PUBLIC.OPERATION (OPERATION_NAME)
VALUES ('REMOVE'),
       ('ADD'),
       ('UPDATE');

