INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (1, 'Комедия');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (2, 'Драма');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (3, 'Мультфильм');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (4, 'Триллер');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (5, 'Документальный');

INSERT INTO PUBLIC.LIST_OF_GENRES (GENRE_ID, GENRE_NAME)
VALUES (6, 'Боевик');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('G');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('PG');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('PG-13');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('R');

INSERT INTO PUBLIC.LIST_OF_MPAS (MPA_NAME)
VALUES ('NC-17');

INSERT INTO PUBLIC.EVENT_TYPE (TYPE_NAME)
VALUES ('LIKE'),
       ('REVIEW'),
       ('FRIEND');

INSERT INTO PUBLIC.OPERATION (OPERATION_NAME)
VALUES ('REMOVE'),
       ('ADD'),
       ('UPDATE');

